apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podspec
  name: podspec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podspec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: podspec
    spec:
      serviceAccountName: podspec
      containers:
      - image: cnpg-i-podspec:latest
        name: cnpg-i-podspec
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
        - plugin
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
        resources: {}
      volumes:
      - name: server
        secret:
          secretName: podspec-server-tls
      - name: client
        secret:
          secretName: podspec-client-tls
