apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: podspec
  namespace: cnpg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podspec
subjects:
- kind: ServiceAccount
  name: podspec
  namespace: cnpg-system
