apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: podspec
  namespace: cnpg-system
rules:
- apiGroups:
  - ""
  resources:
  - podtemplates
  verbs:
  - get
