apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podspec-server
spec:
  secretName: podspec-server-tls
  commonName: "podspec"
  dnsNames:
    - podspec

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
